package log_test

import (
	"testing"

	"regexp"

	"github.com/theplant/appkit/kerrs"
	"github.com/theplant/appkit/log"
)

func TestLog(t *testing.T) {
	l := log.Default()
	err := l.Crit().Log("msg", "hello")
	if err != nil {
		t.Error(err)
	}
}

func TestLogError(t *testing.T) {
	_, err := regexp.Compile("[")
	err2 := kerrs.Wrapv(err, "wrong regexp", "testcase", "TestLogError", "lineno", 23)
	l := log.Default()
	l.WithError(err2).Log()
	// level=error ts=2017-05-03T16:37:00.330516055+08:00 caller=<autogenerated>:1 testcase=TestLogError lineno=23 msg="wrong regexp => error parsing regexp: missing closing ]: `[`" stacktrace="wrong regexp testcase=TestLogError lineno=23: error parsing regexp: missing closing ]: `[`\ngithub.com/theplant/appkit/kerrs.Wrapv\n\t/Users/sunfmin/gopkg/src/github.com/theplant/appkit/kerrs/errors.go:22\ngithub.com/theplant/appkit/log_test.TestLogError\n\t/Users/sunfmin/gopkg/src/github.com/theplant/appkit/log/log_test.go:22\ntesting.tRunner\n\t/usr/local/Cellar/go/1.8/libexec/src/testing/testing.go:657\nruntime.goexit\n\t/usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197\n\nerror parsing regexp: missing closing ]: `[`\n\n"

}
