apiVersion: v1
kind: List
items:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: app
      labels:
        name: app
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          securityContext:
            runAsNonRoot: true
          # this needs to match Terraform state's `module.app-role.name`.
          serviceAccountName: app
          containers: &containertemplate
          - name: app
            image: appkit-credentials-example-app
            imagePullPolicy: Never
            envFrom:
            - configMapRef:
                # Makefile generates this configMap before launching
                # the app. It sets variables for:
                # - role for initial Vault authentication
                # - path for Vault AWS secret to fetch AWS IAM credentials
                name: app
          restartPolicy: Never
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: app-failing
      labels:
        name: app-failing
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          securityContext:
            runAsNonRoot: true
          # This job will not be able to authenticate with vault.
          serviceAccountName: default
          restartPolicy: Never
          containers: *containertemplate
