apiVersion: v1
kind: List
items: 
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vault
      labels:
        app: vault
    spec:
      selector:
        matchLabels:
          app: vault
      template:
        metadata:
          labels:
            app: vault
        spec:
          containers:
          - name: vault
            image: vault
            ports:
            - containerPort: 8200
            envFrom:
            - configMapRef:
                name: vault-config
  - kind: Service
    apiVersion: v1
    metadata:
      name: vault
    spec:
      type: NodePort
      selector:
        app: vault
      ports:
      - protocol: TCP
        port: 8200
        targetPort: 8200
